import { IPlugin } from '@hedron-gl/engine'

export const globalOptionNodesConfig = [
  {
    nodeType: 'param',
    key: 'protocol',
    title: 'Protocol',
    valueType: 'enum',
    options: [
      { value: 'artnet', label: 'ArtNet' },
      { value: 'sacn', label: 'sACN' },
      { value: 'usb', label: 'USB DMX' },
    ],
    defaultValue: 'artnet',
  },
  {
    nodeType: 'param',
    key: 'brightness',
    title: 'Brightness',
    valueType: 'number',
    defaultValue: 1,
    sliderMin: 0,
    sliderMax: 1,
  },
  {
    nodeType: 'param',
    key: 'lerpSpeed',
    title: 'Lerp Speed',
    valueType: 'number',
    defaultValue: 0.2,
    sliderMin: 0,
    sliderMax: 1,
  },
  {
    nodeType: 'param',
    key: 'dither',
    title: 'Temporal Dither',
    valueType: 'boolean',
    defaultValue: true,
  },
  {
    nodeType: 'param',
    key: 'lerpMode',
    title: 'Lerp Mode',
    valueType: 'enum',
    options: [
      { value: 'linear-rgb', label: 'Linear RGB' },
      { value: 'curved-hsb', label: 'Curved HSB' },
    ],
    defaultValue: 'linear-rgb',
  },
  {
    nodeType: 'param',
    key: 'stageWidth',
    title: 'Stage Width',
    valueType: 'number',
    defaultValue: 10,
    sliderMin: 1,
    sliderMax: 50,
  },
  {
    nodeType: 'param',
    key: 'stageDepth',
    title: 'Stage Depth',
    valueType: 'number',
    defaultValue: 10,
    sliderMin: 1,
    sliderMax: 50,
  },
] as const satisfies IPlugin['globalOptionNodesConfig']
